'use strict';
// Room/chat/team transport. Full synchronized PvP rounds are a separate milestone.
(()=>{
 let token='',playerId='',room=null,stream=null,lastTeam='',poller=null;
 const $=s=>document.querySelector(s);
 const node=document.createElement('section');node.className='live-online';node.innerHTML=`<h3>ONLINE / MULTIPLAYER <small>2인 접속 테스트 · 최대 8인 방 구조</small></h3><div class="online-row"><input id="liveName" maxlength="18" placeholder="닉네임" value="실험체"><button id="liveCreate">방 생성</button><input id="liveCode" maxlength="6" placeholder="방 코드"><button id="liveJoin">참가</button></div><p id="liveNotice">서버 연결 대기 · 이 기능은 Node 서버에서 실행해야 해.</p><div id="liveLobby" hidden><div class="online-row"><strong id="liveRoomCode"></strong><button id="liveCopy">초대 주소 복사</button><button id="liveReady">준비</button><button id="liveLeave">퇴장</button></div><div id="livePlayers"></div><div class="online-row"><input id="liveChatInput" maxlength="240" placeholder="채팅 입력"><button id="liveSend">전송</button></div><div id="liveMessages" aria-live="polite"></div><small>현재 단계는 실제 접속·채팅·팀 배치 공유 테스트야. 전투·경제·라운드 정산은 아직 각 브라우저의 로컬 엔진으로 진행돼.</small></div>`;
 document.querySelector('.app')?.insertBefore(node,document.querySelector('.app')?.firstElementChild?.nextSibling||null);
 const notice=t=>{$('#liveNotice').textContent=t};
 const enc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const api=async(action,data={})=>{const r=await fetch('/api/'+action,{method:'POST',headers:{'content-type':'application/json','x-live-token':token},body:JSON.stringify(data)});const j=await r.json();if(!r.ok)throw Error(j.error||'요청 실패');return j};
 async function connect(action,data){try{disconnect(false);const j=await api(action,data);token=j.token;playerId=j.playerId;room=j.room;$('#liveLobby').hidden=false;notice('접속됨 · 방 '+room.code);$('#liveRoomCode').textContent='ROOM '+room.code;history.replaceState(null,'',location.pathname+'?room='+room.code);draw();stream=new EventSource('/api/events?token='+encodeURIComponent(token));stream.addEventListener('state',e=>{room=JSON.parse(e.data);draw()});stream.onerror=()=>notice('연결 재시도 중… 서버가 실행 중인지 확인해.');lastTeam='';poller=setInterval(pushTeam,1200)}catch(e){notice('연결 실패: '+e.message)}}
 function disconnect(leave){if(poller)clearInterval(poller);poller=null;if(stream)stream.close();stream=null;if(leave&&token)api('leave').catch(()=>{});token='';playerId='';room=null;lastTeam='';$('#liveLobby').hidden=true}
 function draw(){if(!room)return;$('#livePlayers').innerHTML=room.players.map(p=>`<div class="online-player"><b>${enc(p.name)}</b> <span>${p.id===playerId?'나':'참가자'} #${p.slot+1}</span> ${p.ready?'✅ 준비':'◻ 대기'} ${p.connected?'● 접속':'○ 재연결 중'}<small>배치 ${p.team.length}/3: ${p.team.map(x=>enc(x.characterId)+' ★'+x.star).join(', ')||'없음'}</small></div>`).join('');const own=room.players.find(p=>p.id===playerId);$('#liveReady').textContent=own?.ready?'준비 취소':'준비';$('#liveMessages').innerHTML=room.messages.map(m=>`<div>${m.system?'<i>시스템</i>':`<b>${enc(m.name)}</b>`}: ${enc(m.text)}</div>`).join('');$('#liveMessages').scrollTop=$('#liveMessages').scrollHeight;const all=room.players.length>=2&&room.players.every(p=>p.ready&&p.connected);notice(all?'전원 준비 완료! (PvP 전투 동기화는 다음 패치 대상)':'방 '+room.code+' · '+room.players.length+'/'+room.maxPlayers+'명')}
 async function pushTeam(){if(!token||!room||typeof teams==='undefined'||!Array.isArray(teams.A))return;const team=teams.A.slice(0,3).map(x=>({characterId:x.characterId,x:x.x,y:x.y,star:x.star}));const current=JSON.stringify(team);if(current===lastTeam)return;lastTeam=current;try{await api('team',{team})}catch(e){lastTeam='';notice(e.message)}}
 $('#liveCreate').onclick=()=>connect('create',{name:$('#liveName').value,maxPlayers:2});$('#liveJoin').onclick=()=>connect('join',{name:$('#liveName').value,code:$('#liveCode').value});$('#liveReady').onclick=async()=>{if(!room)return;const own=room.players.find(p=>p.id===playerId);try{await api('ready',{ready:!own?.ready})}catch(e){notice(e.message)}};$('#liveLeave').onclick=()=>{disconnect(true);notice('퇴장했어.')};$('#liveSend').onclick=async()=>{const field=$('#liveChatInput'),v=field.value.trim();if(!v)return;try{await api('chat',{text:v});field.value=''}catch(e){notice(e.message)}};$('#liveChatInput').onkeydown=e=>{if(e.key==='Enter')$('#liveSend').click()};$('#liveCopy').onclick=()=>{const url=location.origin+location.pathname+'?room='+room.code;navigator.clipboard?.writeText(url).then(()=>notice('초대 주소 복사 완료')).catch(()=>notice(url))};const code=new URL(location.href).searchParams.get('room');if(code)$('#liveCode').value=code.toUpperCase();window.LIVEMultiplayer={getRoom:()=>room,getPlayerId:()=>playerId};
})();
