'use strict';
// M4-02: account -> room -> ready -> local gameplay. True PvP synchronization is NOT implemented here.
(()=>{
  let session=sessionStorage.getItem('live_session')||'',username='',token='',playerId='',room=null,events=null,poller=null,lastTeam='',openedGame=false;
  const $=s=>document.querySelector(s), safe=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  document.body.classList.add('live-gated');
  const gate=document.createElement('section');gate.id='liveGate';gate.innerHTML=`<div class="live-gate-card">
   <div class="live-eyebrow">AGLAIA // L.I.V.E.</div><h1>LIVE</h1><p class="live-sub">Lumia Island Virtual Experiment</p>
   <div id="liveAuth"><h2 id="authTitle">로그인</h2><input id="authId" autocomplete="username" placeholder="아이디 (영문·숫자 3~20자)" maxlength="20"><input id="authPw" type="password" autocomplete="current-password" placeholder="비밀번호 (8자 이상)"><div class="live-line"><button id="authLogin" class="live-primary">로그인</button><button id="authRegister">회원가입</button></div><small>계정은 현재 실행 중인 서버에 저장돼. 공개 인터넷 배포용 인증 시스템은 아니야.</small></div>
   <div id="liveRooms" hidden><div class="live-line"><b id="liveAccount"></b><button id="liveLogout">로그아웃</button></div><h2>멀티플레이 로비</h2><button class="live-primary" id="liveCreate">새 방 만들기 (2인 테스트)</button><div class="live-line"><input id="liveCode" maxlength="6" placeholder="6자리 방 코드"><button id="liveJoin">방 참가</button></div></div>
   <div id="liveWaiting" hidden><div class="live-line"><h2 id="liveRoomName"></h2><button id="liveLeave">퇴장</button></div><p id="liveMemberList"></p><div class="live-line"><button id="liveReady" class="live-primary">준비하기</button><button id="liveStart" hidden>게임 시작 (방장)</button></div><p class="live-help">전원 준비 후 방장이 시작하면 게임 화면으로 이동해.</p></div>
   <p id="liveNotice" role="status">로그인 후 방을 생성하거나 참가해.</p></div>`;document.body.appendChild(gate);
  const dock=document.createElement('aside');dock.id='liveGameChat';dock.hidden=true;dock.innerHTML=`<div class="live-chat-head"><b>LIVE · ROOM <span id="liveGameCode"></span></b><span id="liveGameMembers"></span></div><div id="liveMessages" class="live-chat-log"></div><div class="live-chat-send"><input id="liveChatInput" maxlength="240" placeholder="채팅 입력"><button id="liveSend">전송</button></div><small>온라인 채팅·팀 정보만 동기화됨 · 전투는 아직 각 브라우저 로컬 시뮬레이션</small>`;document.body.appendChild(dock);
  const notice=t=>{$('#liveNotice').textContent=t};
  async function api(action,data={}){const res=await fetch('/api/'+action,{method:'POST',headers:{'content-type':'application/json','x-live-token':token,'x-live-session':session},body:JSON.stringify({...data,session})});const obj=await res.json();if(!res.ok)throw Error(obj.error||'요청 실패');return obj}
  const display=(part)=>{ $('#liveAuth').hidden=part!=='auth';$('#liveRooms').hidden=part!=='rooms';$('#liveWaiting').hidden=part!=='waiting'; };
  function showRoom(){if(!room)return;display('waiting');$('#liveRoomName').textContent='ROOM '+room.code;const own=room.players.find(p=>p.id===playerId);$('#liveMemberList').innerHTML=room.players.map(p=>`<div class="live-member"><b>${safe(p.name)}</b><span>${p.connected?'● 접속':'○ 연결 중'} · ${p.ready?'준비 완료':'대기'}</span></div>`).join('');$('#liveReady').textContent=own?.ready?'준비 취소':'준비하기';const ready=room.players.length>=2&&room.players.every(p=>p.ready&&p.connected);$('#liveStart').hidden=own?.slot!==0;$('#liveStart').disabled=!ready;notice(ready?'모두 준비 완료! 방장이 게임을 시작할 수 있어.':'참가자 모두 준비해야 시작할 수 있어.');if(room.started)openGame();}
  function drawChat(){if(!room)return;$('#liveGameCode').textContent=room.code;$('#liveGameMembers').textContent=room.players.length+'/'+room.maxPlayers;$('#liveMessages').innerHTML=room.messages.map(m=>`<div>${m.system?'<i>시스템</i>':`<b>${safe(m.name)}</b>`}: ${safe(m.text)}</div>`).join('');$('#liveMessages').scrollTop=$('#liveMessages').scrollHeight;}
  function openGame(){if(openedGame)return;openedGame=true;document.body.classList.remove('live-gated');gate.hidden=true;dock.hidden=false;$('#devExit')?.setAttribute('hidden','');if(typeof enterAppMode==='function')enterAppMode('game');$('#devExit')?.setAttribute('hidden','');drawChat();lastTeam='';poller=setInterval(pushTeam,1300);}
  async function pushTeam(){if(!token||!room||!openedGame||typeof teams==='undefined'||!Array.isArray(teams.A))return;const team=teams.A.slice(0,3).map(x=>({characterId:x.characterId,x:x.x,y:x.y,star:x.star}));const str=JSON.stringify(team);if(str===lastTeam)return;lastTeam=str;try{await api('team',{team})}catch(e){lastTeam='';console.warn('배치 공유 실패',e)}}
  function disconnect(){if(poller)clearInterval(poller);poller=null;events?.close();events=null;token='';playerId='';room=null;lastTeam='';}
  async function join(action,payload){try{const j=await api(action,payload);token=j.token;playerId=j.playerId;room=j.room;history.replaceState(null,'',location.pathname+'?room='+room.code);showRoom();events=new EventSource('/api/events?token='+encodeURIComponent(token));events.addEventListener('state',e=>{room=JSON.parse(e.data);if(openedGame)drawChat();else showRoom()});events.onerror=()=>notice('서버 연결 재시도 중…');}catch(e){notice(e.message)}}
  async function logIn(action){try{const j=await api(action,{username:$('#authId').value,password:$('#authPw').value});session=j.session;username=j.username;sessionStorage.setItem('live_session',session);$('#liveAccount').textContent=username;display('rooms');notice(action==='register'?'회원가입 및 로그인 완료!':'로그인 완료!')}catch(e){notice(e.message)}}
  $('#authLogin').onclick=()=>logIn('login');$('#authRegister').onclick=()=>logIn('register');$('#authPw').addEventListener('keydown',e=>{if(e.key==='Enter')$('#authLogin').click()});
  $('#liveLogout').onclick=async()=>{await api('logout').catch(()=>{});session='';username='';sessionStorage.removeItem('live_session');display('auth');notice('로그아웃했어.')};
  $('#liveCreate').onclick=()=>join('create',{maxPlayers:2});$('#liveJoin').onclick=()=>join('join',{code:$('#liveCode').value});
  $('#liveReady').onclick=async()=>{try{const own=room.players.find(p=>p.id===playerId);await api('ready',{ready:!own?.ready})}catch(e){notice(e.message)}};
  $('#liveStart').onclick=async()=>{try{await api('start')}catch(e){notice(e.message)}};
  $('#liveLeave').onclick=async()=>{await api('leave').catch(()=>{});disconnect();display('rooms');notice('방에서 퇴장했어.')};
  $('#liveSend').onclick=async()=>{const text=$('#liveChatInput').value.trim();if(!text)return;try{await api('chat',{text});$('#liveChatInput').value=''}catch(e){console.warn(e.message)}};$('#liveChatInput').addEventListener('keydown',e=>{if(e.key==='Enter')$('#liveSend').click()});
  const code=new URLSearchParams(location.search).get('room');if(code)$('#liveCode').value=code.toUpperCase();
  if(session)api('me').then(j=>{username=j.username;$('#liveAccount').textContent=username;display('rooms')}).catch(()=>{session='';sessionStorage.removeItem('live_session');display('auth')});else display('auth');
  window.LIVEMultiplayer={getRoom:()=>room,getPlayerId:()=>playerId};
})();
