'use strict';
/* M4-11: six interactive local QA minigames. No network, storage or account writes. */
(()=>{
const $=id=>document.getElementById(id), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const games=[
 ['recover','금지구역 보급품 회수','INVENTORY / RISK','가방 배치 · 철수','보급품을 가방의 제한된 칸에 직접 배치하고, 과열되기 전에 철수해.'],
 ['zones','루미아 섬 탐색 작전','EXPLORATION / AP','구역 · 타일 · 경로','구역을 고르고 4×4 지도를 탐색해. 행동력·위험·단서가 경로를 바꿔.'],
 ['divide','전리품 분배 협정','TRUST / CLAIM','전리품 · 심리전','세 차례 전리품 선점. 같은 상자를 두고 나눌지 독식할지 비밀리에 결정해.'],
 ['bomb','AGLAIA 폭발물 해체','ASYMMETRIC / CO-OP','채팅 · 장치 3단계','한 명은 장치, 한 명은 매뉴얼. 채팅으로 협력하고 실제 모듈을 해체해.'],
 ['ultimatum','생존자 간 크레딧 협상','NEGOTIATION / DEAL','역제안 · 합의','총 10C를 놓고 제안·역제안·수락을 주고받아. 합의하지 못하면 추가 보상 없음.'],
 ['craft','긴급 제작 작전','CO-OP / RECIPE','조합 · 작업대','분산된 재료 중 정답을 직접 찾아 공동 작업대에 올리고 장비 3개를 제작해.']
];
let selected='recover',seed=0,g,log=[],rng=Math.random;
const R=n=>Math.floor(rng()*n),pick=a=>a[R(a.length)],shuffle=a=>{const b=[...a];for(let i=b.length-1;i>0;i--){let j=R(i+1);[b[i],b[j]]=[b[j],b[i]]}return b},opp=r=>r==='A'?'B':'A';
function seeded(n){let s=n>>>0;return()=>{s+=0x6d2b79f5;let t=s;t=Math.imul(t^(t>>>15),t|1);t^=t+Math.imul(t^(t>>>7),t|61);return ((t^(t>>>14))>>>0)/4294967296}}
function note(s){log.unshift(s);log=log.slice(0,26)}
function done(message,bonuses){g.finished=true;g.message=message;g.bonus={A:Math.max(0,Math.min(10,bonuses.A||0)),B:Math.max(0,Math.min(10,bonuses.B||0))};note(message)}
function personState(){return {A:{done:false,points:0},B:{done:false,points:0}}}
const ZONES=['숲','병원','공장','항구','성당','학교','절','연못','번화가','골목길','묘지','호텔'];
function dist(a,b){return Math.abs(a%4-b%4)+Math.abs(Math.floor(a/4)-Math.floor(b/4))}
function zoneMap(){const tiles=shuffle(['supply','supply','rare','scanner','risk','risk','trace','trace','empty','empty','empty','empty','empty','empty','empty']);tiles.splice(12,0,'start');return tiles}
function reveal(p){for(let i=0;i<16;i++)if(dist(i,p.pos)<=1)p.seen.add(i)}
function initZone(){let options=shuffle(ZONES).slice(0,3);g.options=options;g.players={};for(const r of ['A','B'])g.players[r]={zone:null,map:zoneMap(),pos:12,seen:new Set([12,8,13]),visited:new Set([12]),ap:8,points:0,risk:0,opened:new Set(),done:false,scan:false};g.deadline=Date.now()+90000}
const shapes=[[[0,0]],[[0,0],[1,0]],[[0,0],[0,1],[1,1]],[[0,0],[1,0],[0,1],[1,1]],[[0,0],[1,0],[2,0]]];
function initRecover(){g.players={};for(const r of ['A','B'])g.players[r]={board:Array(16).fill(-1),packs:Array.from({length:8},(_,i)=>({name:pick(['회수한 배터리','응급 의약품','고급 부품','전자 재료','파손된 장비','보급 식량','감시장치','에너지 팩']),shape:shapes[R(shapes.length)],value:2+R(5),used:false,id:i})),selection:null,rotation:0,heat:0,points:0,done:false}}
function initDivide(){g.round=0;g.scores={A:0,B:0};g.choices={};g.history=[];g.crates=Array.from({length:3},()=>({value:2+R(4),tag:pick(['보급 상자','희귀 물자','연구소 물품','의약품'])}))}
function bombStep(module){const wire=shuffle(['red','blue','yellow','green']);return {type:module,wires:wire,code:pick(['A','B','C']),digits:shuffle([1,2,3,4]),lamps:Array.from({length:4},()=>R(2)),signal:R(2),state:0}}
function bombCorrect(m){if(m.type===0)return m.code==='A'?m.wires.indexOf('red'):m.code==='B'?m.wires.indexOf('blue'):m.wires.indexOf('yellow');if(m.type===1)return m.code==='A'?m.digits.indexOf(1):m.code==='B'?m.digits.indexOf(4):m.digits.indexOf(2);return m.signal===0?m.lamps.indexOf(1)>=0?m.lamps.indexOf(1):0:m.lamps.lastIndexOf(0)>=0?m.lamps.lastIndexOf(0):3}
function initBomb(){g.operator=pick(['A','B']);g.stage=0;g.modules=shuffle([0,1,2]).map(type=>bombStep(type));g.chat=[];g.deadline=Date.now()+120000}
function initUltimatum(){g.offer=null;g.offerCount=0;g.proposer=pick(['A','B']);g.timeline=[]}
function initCraft(){const target=shuffle(LIVEItems.recipes).slice(0,3).map(row=>({name:row[0],materials:LIVEItems.all[row[0]].materials}));g.orders=target;g.index=0;g.tray={A:null,B:null};g.misses=0;g.inventory={A:[],B:[]};for(let i=0;i<target.length;i++){g.inventory.A.push({name:target[i].materials[0],id:`A${i}`});g.inventory.B.push({name:target[i].materials[1],id:`B${i}`})}for(const r of ['A','B']){g.inventory[r].push({name:pick(LIVEItems.baseNames),id:`${r}3`},{name:pick(LIVEItems.baseNames),id:`${r}4`});g.inventory[r]=shuffle(g.inventory[r])}g.showRecipe=false}
function newGame(id=selected,forced=null){selected=id;seed=forced===null?(Date.now()^Math.floor(Math.random()*0x7fffffff))>>>0:forced>>>0;rng=seeded(seed);log=[];g={view:'A',finished:false,bonus:{A:0,B:0}};
if(id==='recover')initRecover();if(id==='zones')initZone();if(id==='divide')initDivide();if(id==='bomb')initBomb();if(id==='ultimatum')initUltimatum();if(id==='craft')initCraft();note('새 QA 세션. 온라인 계정·재화에는 영향 없음.');render()}
function roleTabs(){return `<div class="qa-role-tabs"><button data-action="view" data-role="A" aria-pressed="${g.view==='A'}">A 화면</button><button data-action="view" data-role="B" aria-pressed="${g.view==='B'}">B 화면</button></div>`}
const btn=(text,action,val='',disabled=false,cls='qa-cta secondary')=>`<button type="button" class="${cls}" data-action="${action}" data-val="${esc(val)}" ${disabled?'disabled':''}>${text}</button>`;
const stat=(name,v)=>`<div class="qa-statline"><span>${name}</span><strong>${v}</strong></div>`;
function panel(inner){return `<div class="qa-console">${inner}</div>${g.finished?`<div class="qa-result"><span class="qa-kicker">QA RESULT</span><h3>${esc(g.message)}</h3><p>가상 보상 · A ${3+g.bonus.A}C / B ${3+g.bonus.B}C (각 기본 3C 포함)</p>${btn('같은 시드 재시작','replay','','', 'qa-cta')}</div>`:''}`}
function recoverUI(){let p=g.players[g.view],active=!p.done&&!g.finished,bag=p.board;let tile=(s,i)=>{if(s===-1)return `<button type="button" class="qa-grid-cell empty" data-action="put" data-val="${i}" ${!active?'disabled':''}><span>+</span></button>`;return `<button type="button" class="qa-grid-cell filled" disabled title="${esc(p.packs[s].name)}">◆</button>`};return panel(`${roleTabs()}<div class="qa-info-row"><span>RESTRICTED ZONE / SALVAGE</span><b>과열 ${p.heat}/6 · 확보 ${p.points}점</b></div><h3 class="qa-question">물자를 가방에 직접 배치해.</h3><p class="qa-instructions">물자를 선택해 회전한 뒤 빈 칸을 눌러 배치해. 일부러 가방을 비워둘 수도 있어. 과열 6에 도달하면 자동 회수 종료. 기본 보상은 유지돼.</p><div class="qa-two"><div><div class="qa-panel-heading">회수 가방 / 4 × 4</div><div class="qa-tile-grid">${bag.map(tile).join('')}</div>${btn('선택한 물자 90° 회전','rotate','',!active||p.selection===null)}${stat('현재 선택',p.selection===null?'없음':esc(p.packs[p.selection].name))}</div><div><div class="qa-panel-heading">현장 물자 목록</div><div class="qa-stack">${p.packs.map((item,i)=>`<button type="button" class="qa-loot ${p.selection===i?'picked':''}" data-action="take" data-val="${i}" ${!active||item.used?'disabled':''}><b>${esc(item.name)}</b><small>${item.shape.length}칸 · 가치 ${item.value}점 ${item.used?'· 적재 완료':''}</small></button>`).join('')}</div></div></div><div class="qa-row">${btn('회수하고 철수','stop','',!active,'qa-cta')}${btn('가방 초기화 (회수 전용)','clear','',!active)}</div>`)}
function regionUI(){const p=g.players[g.view];if(!p.zone){return panel(`${roleTabs()}<span class="qa-kicker">LUMIA / AREA SELECT · <span id="qaTimeLeft">90s</span></span><h3 class="qa-question">루미아 섬에서 탐색 구역 선택</h3><div class="qa-island"><div class="qa-island-caption">구역 선택용 임시 지도 · 정식 루미아 섬 이미지 별도 연결 예정</div><div class="qa-region-list">${g.options.map((z,i)=>`<button class="qa-region" data-action="zone" data-val="${i}" ${g.finished?'disabled':''}><small>AREA 0${i+1}</small><b>${esc(z)}</b><span>${['균형형 탐색','물자 밀집','위험 지역'][i]}</span></button>`).join('')}</div></div><p class="qa-instructions">두 플레이어는 같은 후보 3곳에서 각자 선택하고, 서로 다른 개인 맵을 탐험해.</p>`)}
let visible=i=>p.visited.has(i)?({start:'●',empty:'·',supply:'▣',rare:'◈',risk:'!',scanner:'⌁',trace:'⌕'}[p.map[i]]):p.seen.has(i)?({start:'●',empty:'·',supply:'□',rare:'◇',risk:'△',scanner:'⌁',trace:'⌕'}[p.map[i]]):'?';
return panel(`${roleTabs()}<div class="qa-info-row"><span>LUMIA / ${esc(p.zone)} · <span id="qaTimeLeft">90s</span></span><b>AP ${p.ap}/8 · 물자 ${p.points}점 · 위험 ${p.risk}/3</b></div><h3 class="qa-question">직접 이동하고, 수색하고, 철수해.</h3><div class="qa-two"><div><div class="qa-panel-heading">4 × 4 탐색 지도</div><div class="qa-tile-grid">${p.map.map((t,i)=>`<button class="qa-grid-cell ${p.pos===i?'current':p.visited.has(i)?'visited':p.seen.has(i)?'seen':'fog'} ${t==='risk'&&p.seen.has(i)?'danger-tile':''}" data-action="walk" data-val="${i}" ${g.finished||p.done||p.ap<=0?'disabled':''} title="${p.seen.has(i)?(p.visited.has(i)?t:'수상한 지형 신호'):'미탐색'}">${p.pos===i?'◆':visible(i)}</button>`).join('')}</div><p class="qa-caption">◆ 현재 위치 · □ 보급 신호 · ◇ 희귀 · △ 위험 · ⌁ 스캐너 · ? 미탐색</p></div><div><div class="qa-panel-heading">현장 제어</div>${stat('출발 지점','좌하단')}${stat('현재 타일',esc(({start:'출발 지점',empty:'일반 지형',supply:'보급 상자',rare:'희귀 상자',risk:'위험 지형',scanner:'탐지 장치',trace:'야생 흔적'})[p.map[p.pos]]))}${stat('안전한 철수', '언제든 가능')}<p class="qa-instructions">상하좌우 인접 타일 클릭으로 1 AP 이동. 처음 가는 곳의 지형은 인접 단서로 예상할 수 있어. 위험 지역은 AP 추가 소모. 상자는 도착 후 수색해야 해.</p><div class="qa-row">${btn('현재 칸 수색·작동','inspect','',g.finished||p.done||p.opened.has(p.pos)||!['supply','rare','scanner','trace'].includes(p.map[p.pos])||p.ap<1)}${btn('안전 철수','retreat','',g.finished||p.done,'qa-cta')}</div></div></div>`)}
function divideUI(){let rounds=g.round<3;let choose=g.choices[g.view];return panel(`${roleTabs()}<span class="qa-kicker">JOINT LOOT / ROUND ${Math.min(3,g.round+1)} OF 3</span><h3 class="qa-question">같은 전리품을 노릴까, 나눠서 챙길까?</h3>${stat('현재 누적 성과',`A ${g.scores.A}점 · B ${g.scores.B}점`)}<p class="qa-instructions">각자 상자 하나를 고르고 '분배' 또는 '독식'을 비공개로 선택해. 다른 상자를 고르면 방해 없이 확보. 같은 상자라면 분배·배신 결과에 따라 보상이 갈려. 총 3차전.</p><div class="qa-crates">${g.crates.map((c,i)=>`<button class="qa-crate ${choose?.box===i?'picked':''}" data-action="crate" data-val="${i}" ${!rounds||!!choose?'disabled':''}><small>CRATE ${i+1}</small><strong>${c.value}점</strong><span>${esc(c.tag)}</span></button>`).join('')}</div><div class="qa-row">${['share','grab'].map(x=>btn(`${x==='share'?'분배':'독식'} 방식 선택`,'stance',x,!rounds||!choose||!!choose.stance,x==='share'?'qa-cta secondary':'qa-cta danger')).join('')}</div><p class="qa-hint">현재 ${choose?`상자 ${choose.box+1} / ${choose.stance==='share'?'분배':'독식'} 선택 완료. 상대 차례를 진행해.`:`상자를 먼저 고르고 그 다음 분배 방식 선택. 선택은 상대에게 비공개.`}</p>${g.history.length?`<div class="qa-divider"></div>${g.history.map(t=>`<p class="qa-caption">${esc(t)}</p>`).join('')}`:''}`)}
function bombUI(){let m=g.modules[Math.min(g.stage,2)],op=g.view===g.operator,manual=g.view!==g.operator;
const wireNames={red:'빨강',blue:'파랑',yellow:'노랑',green:'초록'};
let controls=m.type===0?`<div class="qa-wire-grid">${m.wires.map((x,i)=>`<button class="qa-wire-card" data-action="defuse" data-val="${i}" ${g.finished?'disabled':''}><span class="qa-wire ${x}"></span><b>${i+1}번 ${wireNames[x]}</b><small>절단</small></button>`).join('')}</div>`:m.type===1?`<div class="qa-wire-grid">${m.digits.map((x,i)=>`<button class="qa-keypad" data-action="defuse" data-val="${i}" ${g.finished?'disabled':''}>${x}</button>`).join('')}</div>`:`<div class="qa-wire-grid">${m.lamps.map((v,i)=>`<button class="qa-lamp" data-action="defuse" data-val="${i}" ${g.finished?'disabled':''}><i class="${v?'on':''}"></i><b>스위치 ${i+1}</b></button>`).join('')}</div>`;
const manuals=['A: 빨간 전선 / B: 파란 전선 / C: 노란 전선을 절단. 해당 색은 반드시 하나 존재해.','A: 숫자 1 / B: 숫자 4 / C: 숫자 2가 적힌 버튼을 누르기.','신호 0이면 왼쪽에서 첫 번째 켜진 램프의 스위치, 신호 1이면 오른쪽에서 첫 번째 꺼진 램프의 스위치. 해당 상태가 없으면 1번(0) / 4번(1).'];
return panel(`${roleTabs()}<span class="qa-kicker">AGLAIA / DEFUSAL STAGE ${Math.min(g.stage+1,3)} OF 3 · <span id="qaTimeLeft">120s</span></span><h3 class="qa-question">${op?'폭발물 장치 담당':'해체 매뉴얼 담당'}</h3><div class="qa-progress">${[0,1,2].map(i=>`<span class="qa-pip ${i<g.stage?'active':''}"></span>`).join('')}</div>${op?`<div class="qa-device"><div class="qa-device-label">MODULE ${m.type+1} · CODE ${m.code} ${m.type===2?`· SIGNAL ${m.signal}`:''}</div>${controls}</div><p class="qa-instructions">매뉴얼 담당은 지금 화면을 볼 수 없어. 장치 정보를 채팅으로 전달하고 지시를 받아 직접 조작해. 고의로 다른 곳을 눌러도 돼.</p>`:`<div class="qa-manual"><b>해체 매뉴얼 / 절차 ${m.type+1}</b><p>${esc(manuals[m.type])}</p></div><p class="qa-instructions">어느 색이 몇 번인지, 장치 코드가 무엇인지 채팅으로 물어봐. 잘못 알려줘도 게임이 막지 않아.</p>`}<div class="qa-chat"><div class="qa-chat-lines">${g.chat.length?g.chat.map(v=>`<p><b>${esc(v.from)}:</b> ${esc(v.text)}</p>`).join(''):'<p>통신 대기 중. 정보를 교환해 봐.</p>'}</div><div class="qa-chat-input"><input id="qaChatText" class="qa-input" maxlength="160" placeholder="${g.view}의 메시지 입력" ${g.finished?'disabled':''}>${btn('전송','chat','',g.finished)}</div></div>`)}
function moneyChips(offer,receiver){return `<div class="qa-coinline">${Array.from({length:10},(_,i)=>`<span class="qa-coin ${i<offer?'mine':'theirs'}">C</span>`).join('')}</div><div class="qa-info-row"><span>${receiver}: ${offer}C</span><b>상대: ${10-offer}C</b></div>`}
function ultimatumUI(){const isPending=g.offer!==null,turn=isPending?opp(g.offer.by):g.proposer,active=turn===g.view;const amount=5;
return panel(`${roleTabs()}<span class="qa-kicker">NEGOTIATION / ${g.offerCount} OF 3 PROPOSALS</span><h3 class="qa-question">10C를 어떻게 나눌까?</h3><p class="qa-instructions">최대 세 번의 제안. 상대가 수락하면 합의 성립. 불만이라면 거절하거나 역제안할 수 있지만, 세 번째까지 합의하지 못하면 둘 다 추가 보상 0C.</p>${g.offer?`<div class="qa-order"><small>현재 제안자 ${g.offer.by}</small><b>${g.offer.by} ${g.offer.amount}C · ${opp(g.offer.by)} ${10-g.offer.amount}C</b>${moneyChips(g.offer.amount,g.offer.by)}</div>`:`<div class="qa-hint">현재 제안 차례: ${g.proposer}. 상대는 제안을 기다려.</div>`}${!isPending&&active?`<div class="qa-field"><label>내 몫 <strong id="qaShareOut">5C</strong> / 상대 <strong id="qaOtherOut">5C</strong></label><input id="qaShare" type="range" min="0" max="10" value="5" step="1"></div>${moneyChips(amount,g.view)}${btn('분배안 제안','offer','',g.finished,'qa-cta')}`:isPending&&active?`<div class="qa-row">${btn('이 제안 수락','accept','',g.finished,'qa-cta')}${g.offerCount<3?btn('거절하고 역제안','counter','',g.finished):btn('최종 거절','reject','',g.finished,'qa-cta danger')}</div>`:`<p class="qa-hint">${turn}의 결정을 기다리고 있어. 상단에서 역할을 바꿔 테스트해.</p>`}<div class="qa-divider"></div><div class="qa-panel-heading">협상 기록</div>${g.timeline.length?g.timeline.map(x=>`<p class="qa-caption">${esc(x)}</p>`).join(''):'<p class="qa-caption">아직 제안 없음</p>'}`)}
function craftUI(){const idx=g.index,order=g.orders[Math.min(idx,2)],mine=g.inventory[g.view];const stored=g.tray;const recipe=LIVEItems.all[order.name]?.materials||[];return panel(`${roleTabs()}<span class="qa-kicker">AGLAIA / JOINT CRAFT ${Math.min(idx+1,3)} OF 3</span><h3 class="qa-question">의뢰 장비를 직접 조합해.</h3><div class="qa-order"><small>제작 의뢰 ${idx+1}/3</small><b>${esc(order.name)}</b><p>${g.showRecipe?`레시피: ${esc(recipe.join(' + '))}`:'조합표를 열면 필요한 두 기본 재료를 확인할 수 있어.'}</p>${btn(g.showRecipe?'조합표 닫기':'이번 레시피 확인','recipe','',g.finished)}</div><div class="qa-crafting"><div><div class="qa-panel-heading">${g.view} 보유 재료</div><div class="qa-stack">${mine.map(item=>`<button class="qa-loot" data-action="load" data-val="${esc(item.id)}" ${g.finished?'disabled':''}><b>${esc(item.name)}</b><small>선택해서 내 작업대 슬롯에 올리기</small></button>`).join('')||'<div class="qa-hint">남은 재료 없음</div>'}</div></div><div><div class="qa-panel-heading">공동 작업대</div><div class="qa-belt">${['A','B'].map(r=>`<div class="qa-belt-slot"><small>${r} 슬롯</small><strong>${stored[r]?esc(stored[r].name):'재료 대기'}</strong></div>`).join('')}</div><p class="qa-instructions">두 플레이어가 재료 하나씩 올린 뒤 조합 실행. 틀리면 재료는 그대로지만 장치 과열이 쌓여. 오조합 세 번이면 제작 종료.</p>${btn('작업대 조합 실행','combine','',g.finished||!stored.A||!stored.B,'qa-cta')}${stat('과열 누적',`${g.misses} / 3`)}${btn('내 슬롯의 재료 되돌리기','unload','',g.finished||!stored[g.view])}</div></div>`)}
function status(r){if(g.finished)return `종료 · 총 ${3+g.bonus[r]}C (가상)`;if(selected==='recover')return g.players[r].done?'철수 완료':`가방 ${g.players[r].board.filter(x=>x>=0).length}/16칸`;if(selected==='zones')return g.players[r].done?'탐색 종료':g.players[r].zone?`${g.players[r].zone} / AP ${g.players[r].ap}`:'구역 선택 대기';if(selected==='divide')return g.choices[r]?.stance?'선택 완료 · 비공개':`제 ${Math.min(3,g.round+1)}차 선택 대기`;if(selected==='bomb')return g.operator===r?'폭발물 담당':'매뉴얼 담당';if(selected==='ultimatum')return g.offer===null?`${g.proposer} 제안 차례`:`${opp(g.offer.by)}의 답변 대기`;if(selected==='craft')return g.tray[r]?'재료 투입 완료':'재료 투입 대기';return '진행 중'}
function render(){const info=games.find(x=>x[0]===selected);$('qaGameNav').innerHTML=games.map((x,i)=>`<button type="button" class="qa-game-tab" data-select="${x[0]}" aria-current="${selected===x[0]}"><span class="qa-tab-num">0${i+1} / 06</span><b>${esc(x[1])}</b><small>${esc(x[3])}</small></button>`).join('');$('qaGameType').textContent=info[2];$('qaTitle').textContent=info[1];$('qaDescription').textContent=info[4];$('qaSeedDisplay').textContent='SEED '+seed;$('qaParticipants').innerHTML=['A','B'].map(r=>`<div class="qa-person ${g.finished?'qa-done':''}"><div class="qa-person-top"><b>플레이어 ${r}</b><small>${status(r)}</small></div><p>${selected==='zones'?'개인형 미니게임':selected==='bomb'?'협력 · 정보 비대칭':'QA 전용 · 역할 전환 가능'}</p></div>`).join('');$('qaHistory').innerHTML=log.map(s=>`<p>${esc(s)}</p>`).join('');$('qaStage').innerHTML=selected==='recover'?recoverUI():selected==='zones'?regionUI():selected==='divide'?divideUI():selected==='bomb'?bombUI():selected==='ultimatum'?ultimatumUI():craftUI()}
function tryFinishPlayers(kind){if(g.players.A.done&&g.players.B.done){const b={};for(const r of ['A','B'])b[r]=kind==='zones'?Math.min(5,Math.floor(g.players[r].points/2)+(g.players[r].risk<3?1:0)):Math.min(5,Math.floor(g.players[r].points/5));done(kind==='zones'?'루미아 섬 탐색 종료':'보급품 회수 종료',b)}}
function action(a,v='',role=null){if(a==='replay'){newGame(selected,seed);return}if(a==='view'){g.view=role;render();return}if(g.finished)return;const r=g.view;
if(selected==='recover'){
 const p=g.players[r];if(p.done)return;
 if(a==='take'){const i=Number(v);if(p.packs[i]&&!p.packs[i].used){p.selection=i;p.rotation=0}}
 if(a==='rotate')p.rotation=(p.rotation+1)%4;
 if(a==='clear'){p.board.fill(-1);p.packs.forEach(i=>i.used=false);p.heat=0;p.points=0;p.selection=null}
 if(a==='put'&&p.selection!==null){const i=Number(v),item=p.packs[p.selection],rot=(x,y)=>{for(let j=0;j<p.rotation;j++)[x,y]=[-y,x];return [x,y]};let pts=item.shape.map(([x,y])=>rot(x,y));let mx=Math.min(...pts.map(x=>x[0])),my=Math.min(...pts.map(x=>x[1]));pts=pts.map(([x,y])=>[x-mx+i%4,y-my+Math.floor(i/4)]);let cells=pts.map(([x,y])=>x>=0&&x<4&&y>=0&&y<4?y*4+x:-1);
 if(!item.used&&cells.every(x=>x>=0&&p.board[x]===-1)){for(const c of cells)p.board[c]=p.selection;item.used=true;p.points+=item.value;p.heat++;note(`${r}: ${item.name} 적재 성공 (${cells.length}칸)`);p.selection=null;if(p.heat>=6){p.done=true;note(`${r}: 금지구역 경보 · 자동 철수`)}}else note('가방에 들어가지 않아. 물자를 회전하거나 다른 위치를 골라.');}
 if(a==='stop'){p.done=true;note(`${r}: 보급품 회수 종료`)}tryFinishPlayers('recover')}
if(selected==='zones'){
 const p=g.players[r];if(p.done)return;if(a==='zone'&&!p.zone){p.zone=g.options[Number(v)];note(`${r}: ${p.zone} 탐색 진입`)}
 else if(a==='walk'&&p.zone){const n=Number(v);if(n>=0&&n<16&&dist(p.pos,n)===1&&p.ap>0){let fee=1+(p.map[n]==='risk'?1:0);if(p.ap>=fee){p.ap-=fee;p.pos=n;p.visited.add(n);reveal(p);if(p.map[n]==='risk'){p.risk++;note(`${r}: 위험 지형 진입 · AP ${fee} 소모`)}if(p.risk>=3){p.done=true;note(`${r}: 위험 누적으로 긴급 철수`)}}else note(`${r}: 이 경로는 행동력이 부족해.`)}else note('상하좌우 인접 칸으로만 이동할 수 있어.')}
 else if(a==='inspect'&&p.zone&&!p.opened.has(p.pos)&&p.ap>0){const t=p.map[p.pos];if(['supply','rare','scanner','trace'].includes(t)){p.ap--;p.opened.add(p.pos);if(t==='supply')p.points+=2;if(t==='rare'){p.points+=5;p.risk++}if(t==='trace'){p.points++;for(let i=0;i<16;i++)if(dist(i,p.pos)<=2)p.seen.add(i)}if(t==='scanner')for(let i=0;i<16;i++)p.seen.add(i);note(`${r}: ${t} 조사 · 현재 물자 ${p.points}`)}}
 if(a==='retreat'){p.done=true;note(`${r}: ${p.zone||'미선택'} 탐색 종료`)}if(p.ap===0||p.risk>=3)p.done=true;tryFinishPlayers('zones')}
if(selected==='divide'){
 if(a==='crate'&&!g.choices[r]?.stance){g.choices[r]={box:Number(v),stance:null}}
 if(a==='stance'&&g.choices[r]&&!g.choices[r].stance){g.choices[r].stance=v;note(`${r}: 선택 제출 (비공개)`)}
 if(g.choices.A?.stance&&g.choices.B?.stance){const A=g.choices.A,B=g.choices.B;let b={A:0,B:0};if(A.box!==B.box){b.A=g.crates[A.box].value;b.B=g.crates[B.box].value}else{let value=g.crates[A.box].value;if(A.stance==='share'&&B.stance==='share'){b.A=Math.ceil(value/2);b.B=Math.ceil(value/2)}else if(A.stance==='grab'&&B.stance==='grab'){}else{b[A.stance==='grab'?'A':'B']=value}}g.scores.A+=b.A;g.scores.B+=b.B;g.history.push(`제 ${g.round+1}차 / A ${A.box+1}번-${A.stance==='share'?'분배':'독식'} · B ${B.box+1}번-${B.stance==='share'?'분배':'독식'} / +${b.A}, +${b.B}`);g.round++;g.choices={};g.crates=Array.from({length:3},()=>({value:2+R(4),tag:pick(['보급 상자','희귀 물자','연구소 물품','의약품'])}));if(g.round>=3)done('전리품 분배 종료',{A:Math.min(5,Math.floor(g.scores.A/2)),B:Math.min(5,Math.floor(g.scores.B/2))})}}
if(selected==='bomb'){
 if(a==='chat'){const t=$('qaChatText')?.value.trim();if(t){g.chat.push({from:r,text:t.slice(0,160)});note(`${r}: 채팅 전송`)}}
 if(a==='defuse'&&r===g.operator){const m=g.modules[g.stage],correct=bombCorrect(m),chosen=Number(v);if(chosen===correct){g.stage++;note(`${r}: 장치 ${g.stage}/3 해체 성공`);if(g.stage>=3)done('폭발물 해체 성공 · 공동 보상 획득',{A:6,B:6})}else{note(`${r}: 장치 오작동! 정답은 ${correct+1}번째 조작이었어.`);done('폭발물 해체 실패 · 기본 보상 유지',{A:0,B:0})}}}
if(selected==='ultimatum'){
 if(a==='offer'&&g.offer===null&&r===g.proposer){const amount=Math.max(0,Math.min(10,Number($('qaShare')?.value??5)));g.offer={by:r,amount};g.offerCount++;g.timeline.push(`${r}: 본인 ${amount}C / 상대 ${10-amount}C 제안`);note(`${r}: 분배안을 제안했어.`)}
 if(g.offer&&r===opp(g.offer.by)){
 if(a==='accept'){const pay={A:0,B:0};pay[g.offer.by]=g.offer.amount;pay[r]=10-g.offer.amount;done('크레딧 협상 합의',{A:pay.A,B:pay.B})}
 if(a==='reject'){done('협상 결렬 · 추가 보상 없음',{A:0,B:0})}
 if(a==='counter'&&g.offerCount<3){g.timeline.push(`${r}: 이전 제안 거절 · 역제안 차례`);g.proposer=r;g.offer=null}}
 }
if(selected==='craft'){
 if(a==='recipe')g.showRecipe=!g.showRecipe;
 if(a==='load'){const i=g.inventory[r].findIndex(x=>x.id===v);if(i>=0){if(g.tray[r])g.inventory[r].push(g.tray[r]);g.tray[r]=g.inventory[r].splice(i,1)[0];note(`${r}: 작업대에 재료 올림`)}}
 if(a==='unload'&&g.tray[r]){g.inventory[r].push(g.tray[r]);g.tray[r]=null}
 if(a==='combine'&&g.tray.A&&g.tray.B){const result=LIVEItems.craft(g.tray.A.name,g.tray.B.name);if(result===g.orders[g.index].name){g.index++;g.tray={A:null,B:null};g.showRecipe=false;note(`장비 제작 성공: ${result} (${g.index}/3)`);if(g.index===3)done('긴급 제작 작전 성공 · 공동 제작 3개 완료',{A:6,B:6})}else{g.misses++;note(`오조합! 제작 결과 ${result||'실패'} / 과열 ${g.misses}/3`);if(g.misses>=3)done('제작 장치 과열 · 작업 종료',{A:g.index*2,B:g.index*2})}}}
render()}
$('qaGameNav').addEventListener('click',e=>{const b=e.target.closest('[data-select]');if(b)newGame(b.dataset.select)});
$('qaStage').addEventListener('click',e=>{const b=e.target.closest('[data-action]');if(b&&!b.disabled)action(b.dataset.action,b.dataset.val,b.dataset.role)});
$('qaStage').addEventListener('input',e=>{if(e.target.id==='qaShare'){$('qaShareOut').textContent=e.target.value+'C';$('qaOtherOut').textContent=(10-Number(e.target.value))+'C'}});
$('qaStage').addEventListener('keydown',e=>{if(e.key==='Enter'&&e.target.id==='qaChatText')action('chat')});
$('qaRestart').addEventListener('click',()=>newGame(selected));$('qaReplay').addEventListener('click',()=>newGame(selected,seed));
if(typeof setInterval==='function')setInterval(()=>{const timer=$('qaTimeLeft');if(timer&&g?.deadline)timer.textContent=Math.max(0,Math.ceil((g.deadline-Date.now())/1000))+'s';if(!g?.finished&&g.deadline&&Date.now()>=g.deadline){if(selected==='zones'){for(const r of ['A','B'])g.players[r].done=true;tryFinishPlayers('zones')}else if(selected==='bomb')done('해체 시간 초과',{A:0,B:0});render()}},1000);
window.LIVEQA={select:id=>newGame(id),restart:()=>newGame(selected,seed),snapshot:()=>({selected,seed,game:g,history:log}),act:action};newGame();
})();
